# Use root/example as user/password credentials
# https://dockertraining.readthedocs.io/en/latest/nodejs/angularjs-mongodb.html
version: '3.1'

services:

  mongo1:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: ["--replSet", "rs0"]
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo1
    depends_on:
      - mongo1

  backend:
    build:
      context: ./BackendGestionSolarios
      dockerfile: $PWD/BackendGestionSolarios/Dockerfile.app
    ports:
      - 5300:5300
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo1
    depends_on:
      - mongo1
    volumes:
      - "./BackendGestionSolarios:/opt/node"

  frontend:
    build:
      context: ./FrontendGestionSolarios
      dockerfile: $PWD/FrontendGestionSolarios/Dockerfile.app
    ports:
      - 4200:4200
    depends_on:
      - backend
    volumes:
      - "./FrontendGestionSolarios:/opt/ng"